import React from "react";
import {classifyTone,formatDate,formatBytes} from "../utils";
export function StatusBadge({value}){if(value===null||value===undefined||value==="")return<span className="badge neutral">—</span>;return<span className={"badge "+classifyTone(value)}>{String(value).replaceAll("_"," ")}</span>;}
export function StatCard({label,value,hint}){return<div className="stat-card"><div className="stat-label">{label}</div><div className="stat-value">{value??"—"}</div>{hint?<div className="stat-hint">{hint}</div>:null}</div>;}
export function Section({title,subtitle,actions,children,className=""}){return<section className={"panel "+className}><div className="panel-heading"><div>{title?<h2>{title}</h2>:null}{subtitle?<p className="muted">{subtitle}</p>:null}</div>{actions?<div className="panel-actions">{actions}</div>:null}</div>{children}</section>;}
export function LoadingState({label="Loading data…"}){return<div className="state-card" role="status"><span className="spinner"/>{label}</div>;}
export function EmptyState({title="Nothing to show",message="No records match the current view.",action}){return<div className="state-card empty"><strong>{title}</strong><span>{message}</span>{action?<div>{action}</div>:null}</div>;}
export function ErrorState({error,onRetry,title="Unable to load this view"}){return<div className="state-card error-state" role="alert"><strong>{title}</strong><span>{error?.message||"An unexpected error occurred."}</span>{onRetry?<button className="button secondary" onClick={onRetry}>Retry</button>:null}</div>;}
export function InlineNotice({tone="info",children}){return<div className={"notice "+tone}>{children}</div>;}
export function Button({children,variant="primary",loading=false,disabled=false,...props}){return<button className={"button "+variant} disabled={disabled||loading} {...props}>{loading?"Working…":children}</button>;}
export function ConfirmDialog({open,title,message,confirmLabel="Confirm",danger=false,onCancel,onConfirm,loading=false}){if(!open)return null;return<div className="dialog-backdrop" role="presentation"><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">{title}</h2><p>{message}</p><div className="dialog-actions"><Button variant="secondary" onClick={onCancel} disabled={loading}>Cancel</Button><Button variant={danger?"danger":"primary"} onClick={onConfirm} loading={loading}>{confirmLabel}</Button></div></div></div>;}
export function KeyValueGrid({items}){return<div className="key-grid">{items.map(item=><div className="key-item" key={item.label}><span>{item.label}</span><strong>{item.value??"—"}</strong></div>)}</div>;}
export function DataTable({columns,rows,rowKey,emptyTitle,emptyMessage,onRowClick}){if(!rows.length)return<EmptyState title={emptyTitle} message={emptyMessage}/>;return<div className="table-wrap"><table><thead><tr>{columns.map(column=><th key={column.key}>{column.label}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={rowKey?rowKey(row,index):index} className={onRowClick?"clickable-row":""} tabIndex={onRowClick?0:undefined} onClick={onRowClick?()=>onRowClick(row):undefined} onKeyDown={onRowClick?event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();onRowClick(row);}}:undefined}>{columns.map(column=><td key={column.key}>{column.render?column.render(row):row[column.key]}</td>)}</tr>)}</tbody></table></div>;}
export function Pagination({page,pages,onChange}){if(!pages||pages<=1)return null;return<div className="pagination"><Button variant="secondary" disabled={page<=1} onClick={()=>onChange(page-1)}>Previous</Button><span>Page {page} of {pages}</span><Button variant="secondary" disabled={page>=pages} onClick={()=>onChange(page+1)}>Next</Button></div>;}
export function JsonPanel({value}){return<pre className="json-panel">{JSON.stringify(value??{},null,2)}</pre>;}
export function MetricSampleTable({metric}){const samples=metric?.samples||[];if(!samples.length)return<EmptyState title="No samples" message="The metric has no recorded samples."/>;return<div className="table-wrap"><table><thead><tr><th>Value</th><th>Status</th><th>Warm-up</th><th>Retried</th><th>Captured</th></tr></thead><tbody>{samples.map((sample,index)=><tr key={index}><td>{sample.value} {metric.unit}</td><td><StatusBadge value={sample.status}/></td><td>{sample.warmup?"Yes":"No"}</td><td>{sample.retried?"Yes":"No"}</td><td>{formatDate(sample.captured_at)}</td></tr>)}</tbody></table></div>;}
export function LineChart({title,points=[],valueLabel="",maxPoints=60}){const usable=points.filter(point=>Number.isFinite(Number(point.value))).slice(-maxPoints);if(!usable.length)return<EmptyState title={"No "+title} message="The selected data does not contain numeric samples."/>;const width=760,height=240,pad=42,values=usable.map(point=>Number(point.value)),minimum=Math.min(...values),maximum=Math.max(...values),range=maximum-minimum||1,coords=usable.map((point,index)=>{const x=pad+(index*(width-pad*2))/Math.max(1,usable.length-1);const y=height-pad-((Number(point.value)-minimum)/range)*(height-pad*2);return{...point,x,y};}),path=coords.map((point,index)=>(index?"L":"M")+" "+point.x+" "+point.y).join(" ");return<div className="chart-card"><div className="chart-title">{title}</div><svg viewBox={"0 0 "+width+" "+height} role="img" aria-label={title+" chart"}><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} className="axis"/><line x1={pad} y1={pad} x2={pad} y2={height-pad} className="axis"/><path d={path} className="chart-line" fill="none"/>{coords.map((point,index)=><circle key={index} cx={point.x} cy={point.y} r="3.5" className="chart-dot"><title>{(point.label||"Point "+(index+1))+": "+point.value+" "+valueLabel}</title></circle>)}<text x={pad} y={18} className="chart-label">{String(maximum)} {valueLabel}</text><text x={pad} y={height-8} className="chart-label">{String(minimum)} {valueLabel}</text></svg><div className="chart-table-wrap"><table><thead><tr><th>Label</th><th>Value</th></tr></thead><tbody>{usable.map((point,index)=><tr key={index}><td>{point.label||index+1}</td><td>{point.value} {valueLabel}</td></tr>)}</tbody></table></div></div>;}
export function ArtifactLink({artifact}){if(!artifact)return null;if(!artifact.downloadable)return<span className="muted">Unavailable</span>;return<a className="text-link" href={"/api/v1/artifacts/"+encodeURIComponent(artifact.artifact_id)+"/download"} target="_blank" rel="noreferrer">Download</a>;}
export function Field({label,children,hint}){return<label className="field"><span>{label}</span>{children}{hint?<small>{hint}</small>:null}</label>;}
export function formatArtifact(artifact){return(artifact?.display_name||"Artifact")+" · "+(artifact?.artifact_type||"unknown")+" · "+formatBytes(artifact?.size_bytes);}