from __future__ import annotations

from typing import Protocol

from lib.domain import Artifact, Attempt, Baseline, LifecycleEvent, Run, TestResult


class RepositoryError(RuntimeError):
    """Base error for persistence-layer failures."""


class RepositoryNotFoundError(RepositoryError):
    """Raised when a required record is absent."""


class RepositoryConflictError(RepositoryError):
    """Raised when an immutable or unique record would be duplicated."""


class RunRepository(Protocol):
    def save(self, run: Run) -> None: ...
    def update(self, run: Run) -> None: ...
    def get(self, run_id: str) -> Run | None: ...
    def list(self) -> list[Run]: ...


class AttemptRepository(Protocol):
    def save(self, attempt: Attempt) -> None: ...
    def update(self, attempt: Attempt) -> None: ...
    def get(self, attempt_id: str) -> Attempt | None: ...
    def list_for_run(self, run_id: str) -> list[Attempt]: ...


class TestResultRepository(Protocol):
    def save(self, result: TestResult) -> None: ...
    def get(self, test_result_id: str) -> TestResult | None: ...
    def list_for_attempt(self, attempt_id: str) -> list[TestResult]: ...
    def list_for_run(self, run_id: str) -> list[TestResult]: ...


class ArtifactRepository(Protocol):
    def save(self, artifact: Artifact) -> None: ...
    def get(self, artifact_id: str) -> Artifact | None: ...
    def list_for_run(self, run_id: str) -> list[Artifact]: ...
    def list_all(self) -> list[Artifact]: ...


class EventRepository(Protocol):
    def append(self, event: LifecycleEvent) -> None: ...
    def list_for_run(self, run_id: str) -> list[LifecycleEvent]: ...


class BaselineRepository(Protocol):
    def save(self, baseline: Baseline) -> None: ...
    def get(self, baseline_id: str) -> Baseline | None: ...
    def list_active(self) -> list[Baseline]: ...
