import pytest
import subprocess
import time

def test_8021q_vlan_segregation(system_config, async_sniffer):
    """Validates firmware kernel ability to instantiate and route 802.1Q VLANs on physical uplink ports."""
    ap = system_config["nodes"]["ap"]
    
    # Simulate a wired Ethernet uplink port on the router
    uplink_iface = "eth_uplink"
    vlan_id = 20
    vlan_iface = f"{uplink_iface}.{vlan_id}"
    
    try:
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link add {uplink_iface} type dummy", shell=True)
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link set {uplink_iface} up", shell=True)
        
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link add link {uplink_iface} name {vlan_iface} type vlan id {vlan_id}", shell=True)
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link set {vlan_iface} up", shell=True)
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip addr add 10.20.30.1/24 dev {vlan_iface}", shell=True)
        
        # Validate the routing table natively updated for the VLAN
        route_check = subprocess.run(f"sudo ip netns exec {ap['namespace']} ip route", shell=True, capture_output=True, text=True).stdout
        assert "10.20.30.0/24" in route_check, "VLAN routing table entry was not successfully generated by the firmware kernel."
    finally:
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link delete {uplink_iface} 2>/dev/null", shell=True)

def test_etherchannel_lacp_negotiation(system_config, async_sniffer):
    """Validates LACP bonding driver presence in the firmware kernel."""
    ap = system_config["nodes"]["ap"]
    try:
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link add bond0 type bond mode 802.3ad", shell=True)
        link_check = subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link show bond0", shell=True, capture_output=True, text=True).stdout
        assert "bond0" in link_check and "MASTER" in link_check, "Firmware kernel lacks 802.3ad LACP bonding support."
    finally:
        subprocess.run(f"sudo ip netns exec {ap['namespace']} ip link delete bond0 2>/dev/null", shell=True)
