from __future__ import annotations
from enum import Enum
class FirmwareOperationState(str,Enum):
    REGISTERED="REGISTERED"
    VALIDATED="VALIDATED"
    COMPATIBLE="COMPATIBLE"
    AUTHORIZED="AUTHORIZED"
    UPLOADING="UPLOADING"
    UPLOADED="UPLOADED"
    READY_TO_FLASH="READY_TO_FLASH"
    FLASHING="FLASHING"
    REBOOTING="REBOOTING"
    VERIFYING="VERIFYING"
    VALIDATED_FINAL="VALIDATED_FINAL"
    FAILED="FAILED"
