ctrl_interface=/run/hostapd
interface=wlan0
driver=nl80211
ssid=NetForge_Enterprise
hw_mode=g
channel=6
wmm_enabled=1
auth_algs=1
eapol_version=2
ieee8021x=1
wpa=2
wpa_key_mgmt=WPA-EAP
rsn_pairwise=CCMP
eap_server=1
eap_user_file=config/hostapd.eap_user
ca_cert=config/certs/ca.pem
server_cert=config/certs/server.pem
private_key=config/certs/server.key
