# config/hostapd.conf
interface=wlan0
ssid=StyleFusion_Secure_IoT
driver=nl80211
hw_mode=g
channel=6
wmm_enabled=1

# Authentication and Key Management Security Layer
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK WPA-PSK-SHA256 SAE
ieee80211w=1
wpa_passphrase=NetworkTestingEngine2026
rsn_pairwise=CCMP
