# config/wpa_supplicant.conf
ctrl_interface=/var/run/wpa_supplicant
update_config=1

network={
    ssid="StyleFusion_Secure_IoT"
    psk="NetworkTestingEngine2026"
    key_mgmt=SAE
    ieee80211w=1
}
