ctrl_interface=/var/run/wpa_supplicant
update_config=1

network={
    ssid="StyleFusion_Enterprise"
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="qa_user"
    password="EnterpriseSecret2026"
    phase2="auth=MSCHAPV2"
}
