ctrl_interface=/run/wpa_supplicant
update_config=0
p2p_disabled=1
ap_scan=1
fast_reauth=0
network={
    ssid="NetForge_Enterprise"
    key_mgmt=WPA-EAP
    eap=PEAP
    identity="admin"
    password="Password123!"
    ca_cert="config/certs/ca.pem"
    phase2="auth=MSCHAPV2"
    scan_ssid=1
    frequency=2437
}
